server:
  port: 8080
  tomcat:
    max-swallow-size: -1
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
    show-sql: false

  application:
    name: "java_share_hub"
  mvc:
    static-path-pattern: /static/**
    hidden-method:
      filter:
        enabled: true
  freemarker:
    expose-request-attributes: true
  datasource:
    url: jdbc:h2:./db/java_share_hub;AUTO_SERVER=TRUE
    username: root
    password: qwerty
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:/db/changelog/master.yml
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      resolve-lazily: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: error
    org:
      hibernate:
        type: error
        stat: error
      springframework:
        security: debug
      attractor:
        java_share_hub: debug
    web: info
    sql: error
  logback:
    file: logs/application.log
springdoc:
  api-docs:
    path: /v3/api-docs

